#生产环境
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://139.186.133.169:3366/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: kdw051755
    driver-class-name: com.mysql.cj.jdbc.Driver