#开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://139.186.133.169:3366/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kdw051755
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
shop:
  security:
    jwt-key: kang0517
    token-expired-in: 86400000