#开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://139.186.133.169:3366/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kdw051755
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: 139.186.133.169
    port: 6399
    database: 7
    password: kdw051755.
    # 订阅redis key过期事件
    listen-pattern: __keyevent@7__:expired
shop:
  security:
    jwt-key: kang0517
    token-expired-in: 86400000
  order:
    #最大商品购买数量
    max-sku-limit: 100
    #订单过期事件
    pay-time-limit: 3600
#    微信支付回调主机地址及端口号
    pay-callback-host: http://localhost:8080
#    微信支付回调接口路径
    pay-callback-path: /v1/payment/wx/notify
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q

